# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Yonet\Desktop\exceltoexcelınvoiceui\gelir.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Gelir(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1007, 696)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 10, 1001, 651))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tableWidgetFaturalar_1 = QtWidgets.QTableWidget(self.frame)
        self.tableWidgetFaturalar_1.setGeometry(QtCore.QRect(10, 50, 991, 240))
        self.tableWidgetFaturalar_1.setMaximumSize(QtCore.QSize(16777215, 245))
        self.tableWidgetFaturalar_1.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidgetFaturalar_1.setRowCount(10)
        self.tableWidgetFaturalar_1.setColumnCount(33)
        self.tableWidgetFaturalar_1.setObjectName("tableWidgetFaturalar_1")
        self.tableWidgetFaturalar_2 = QtWidgets.QTableWidget(self.frame)
        self.tableWidgetFaturalar_2.setGeometry(QtCore.QRect(10, 340, 991, 240))
        self.tableWidgetFaturalar_2.setMaximumSize(QtCore.QSize(16777215, 245))
        self.tableWidgetFaturalar_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidgetFaturalar_2.setRowCount(10)
        self.tableWidgetFaturalar_2.setColumnCount(33)
        self.tableWidgetFaturalar_2.setObjectName("tableWidgetFaturalar_2")
        self.pushButton_select_folder = QtWidgets.QPushButton(self.frame)
        self.pushButton_select_folder.setGeometry(QtCore.QRect(950, 300, 51, 30))
        self.pushButton_select_folder.setObjectName("pushButton_select_folder")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(910, 590, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_path_excel = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_path_excel.setGeometry(QtCore.QRect(540, 300, 391, 30))
        self.lineEdit_path_excel.setObjectName("lineEdit_path_excel")
        self.pushButton_doldur = QtWidgets.QPushButton(self.frame)
        self.pushButton_doldur.setGeometry(QtCore.QRect(430, 297, 93, 31))
        self.pushButton_doldur.setObjectName("pushButton_doldur")
        self.pushButton_temizle = QtWidgets.QPushButton(self.frame)
        self.pushButton_temizle.setGeometry(QtCore.QRect(800, 590, 93, 28))
        self.pushButton_temizle.setObjectName("pushButton_temizle")
        self.comboBox_name = QtWidgets.QComboBox(self.frame)
        self.comboBox_name.setGeometry(QtCore.QRect(10, 10, 251, 31))
        self.comboBox_name.setObjectName("comboBox_name")
        self.comboBox_name.addItem("")
        self.comboBox_type = QtWidgets.QComboBox(self.frame)
        self.comboBox_type.setGeometry(QtCore.QRect(290, 10, 211, 31))
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.pushButton_kaydet = QtWidgets.QPushButton(self.frame)
        self.pushButton_kaydet.setGeometry(QtCore.QRect(550, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_kaydet.setFont(font)
        self.pushButton_kaydet.setAutoFillBackground(False)
        self.pushButton_kaydet.setStyleSheet("background-color: rgb(255, 95, 21);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_kaydet.setObjectName("pushButton_kaydet")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1007, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_select_folder.setText(_translate("MainWindow", "..."))
        self.pushButton.setText(_translate("MainWindow", "Create Excel"))
        self.pushButton_doldur.setText(_translate("MainWindow", "Doldur"))
        self.pushButton_temizle.setText(_translate("MainWindow", "Temizle"))
        self.comboBox_name.setItemText(0, _translate("MainWindow", "Hasancan Çakıcıoğlu"))
        self.comboBox_type.setItemText(0, _translate("MainWindow", "e-arşiv"))
        self.comboBox_type.setItemText(1, _translate("MainWindow", "e-fatura"))
        self.pushButton_kaydet.setText(_translate("MainWindow", "Kaydet"))

